### ISSUE TITLE
Support for firmware version detection

### ISSUE THREAD

**Issue by happycube** [simoninns/DomesdayDuplicator#12]
I think I didn't update my DD board correctly, as it captures in test mode @ 60MB/sec in both NTSC and PAL modes regardless of other settings.  It would be nice for the system to have version checks on both FPGA and FX3 programs to ensure upgrades are made correctly.  (thanks!)

**Comment by simoninns** [comment]
It's certainly a nice idea.  I will have a look to see how easy it would be to implement something like that.

**Comment by happycube** [comment]
(It turns out I was programming the chip directly and not the I2C ROM, so my setups giving me 28.8mhz  now.)
