### ISSUE TITLE
Switch from QMake to CMake

### ISSUE THREAD

**Issue by lizardgai4** [simoninns/DomesdayDuplicator#120]
Or from QMake-qt5 to QMake6

As part of a distro hopping adventure, I was able to install this software on Ubuntu, Fedora and Manjaro.  ~~OpenSUSE cannot install it because it was not able to install qmake, at least not with its preferred package manager zypper.~~

EDIT: I got it installed on Ubuntu, Fedora, Manjaro, OpenSUSE, Slackware, Solus and Arch, which should represent all the major Linux distro families.  Here's more detail: https://docs.google.com/document/d/132ycIMMNvdKvrNZSzbckXVEPQVLTnH_YX0Oh3lqtkkQ

**Comment by simoninns** [comment]
Is this an issue, a request or just a comment?  Not sure what is expected from this issue report. I think this is closed due to the accepted CMake PR?

**Comment by lizardgai4** [comment]
@simoninns Yes, this issue is resolved, which is good.  Thanks!
