### ISSUE TITLE
Build instructions broken on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [simoninns/DomesdayDuplicator#129]
The build instructions for the capture application are broken for Ubuntu 22.04 LTS.

For QMake:  QT5 is no longer available in normal repos for 22.04

For CMake:  The following error is outputted:
`CMake Error at CMakeLists.txt:16 (qt_add_resources):
  Unknown CMake command "qt_add_resources".`

**Comment by atsampson** [comment]
For Qt 6, it builds OK with Ubuntu 22.04 and the suggested list of dependencies [in the CI](https://github.com/simoninns/DomesdayDuplicator/blob/master/.github/workflows/tests.yml#L40). The CMake files for Qt are in `qt6-base-dev`, so if the dependency installation succeeded then you should have them. Can you show the full output from running the commands in the instructions, and check whether there's anything odd in your environment (`env`)?

(Qt 5 is still available in 22.04 as well, but the qt5-default package doesn't exist any more.)

**Comment by lizardgai4** [comment]
This is strikingly similar to issue #104

**Comment by simoninns** [comment]
I believe this is fixed now; so closing
