### ISSUE TITLE
GGV Calibrations Disc 1069 vs earlier versions

### ISSUE THREAD

**Issue by 14-4Kbps** [simoninns/DomesdayDuplicator#133]
GGV-1069 was the last calibration disc made and it is a newer version that the one noted in the LD-V4400 service manual. The frames noted on the back of both of the disc jackets appear to note the same exact content on the same exact frames. Is there any difference at all between discs? Thanks.

**Comment by simoninns** [comment]
The only way to know is to get an older version of the disc and compare - unfortunately I only have the 1069 since that was what pioneer still had available.  If you care to duplicate another version of the disc and supply it to the ld-decode project, I'm sure a comparison could be made.
