### ISSUE TITLE
linux DdD GUI cmake script broken

### ISSUE THREAD

**Issue by aiohdfgaiuhg** [simoninns/DomesdayDuplicator#144]
When trying to install DdD GUI on Ubuntu 22.04 

cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .

is met with 

CMake Error at CMakeLists.txt:18 (qt_add_resources):
  Unknown CMake command "qt_add_resources".

-- Configuring incomplete, errors occurred!

**Comment by aiohdfgaiuhg** [comment]
apt install libqt5serialport5 libqt5serialport5-dev fixed the issue

**Comment by atsampson** [comment]
I've checked that these are listed in the installation instructions (well, the Qt 6 equivalents are).
