### ISSUE TITLE
Could the Domesday Duplicator be use with D1 format?

### ISSUE THREAD

**Issue by 27hectormanuel** [simoninns/DomesdayDuplicator#155]
Recently the masters for "ReBoot" have been found but to restore and back them up a D1 player is needed. Theoretically could the DD project help preserve this? 

See ReBoot ReWind [post](https://www.facebook.com/rebootrewind/posts/pfbid02YQa32Fa6ZdUffP8dCKPKUrx5AQRVvjG6Cy3jn12WCqZbDGCkbSexU2Tsf4E6cgZKl)

**Comment by simoninns** [comment]
The correct place to ask this would be the project Discord servers - there you will find people with knowledge of various formats.
