### ISSUE TITLE
PCBWay Part Swap on turn-key build

### ISSUE THREAD

**Issue by salgieri** [simoninns/DomesdayDuplicator#158]
I'm using PCBWay to do a turnkey build of the DdD from this page: https://www.pcbway.com/project/shareproject/DoomsDayDuplicator_Rev_3.html

The build sheet returned by PCBWay has a single replacement for the 4-way Gain adjustment dip switch (401SW).

They are recommending replacing RND 210-00184 with 218-4LPSTR. I took a look at the specs for each, but not being a hardware guy, I can't understand if it's a swap out replacement. I also couldn't find any other mention of this swap before on the wiki.

Or, is there a newer way to get a build devices?

Thanks

**Comment by simoninns** [comment]
The part they suggest should work fine by the looks of it.  The DIP switch is a very generic component, so swapping it out shouldn't cause issues.
