### ISSUE TITLE
Amplitude too low / capture stops

### ISSUE THREAD

**Issue by borisbecks** [simoninns/DomesdayDuplicator#159]
I finally got my hands in a DdD for backups of my VHS and LD treasures and it works... Kind of... I could get it to capture from my VCR (SLV-SE700 with a short lead from the test header) but the amplitude is very low. Even when the DIP switches are set to maximum the GUI under Windows shows an amplitude of 0.25 at best. The result can bei decoded just fine but the capture stops after a few minutes with the message "sequence number mismatch -- Samples have been lost from input!". I tried it with another VCR with another type of tap and Had the same result.

I don't know of that's related to the amplitude issue or If it ist a different problem.

What can I do to resolve this? Is there something wrong with the device?

**Comment by simoninns** [comment]
Hi - For general support please use Discord or IRC.  Here's a link:

https://github.com/happycube/ld-decode/wiki/Social-Media

Thanks!
