### ISSUE TITLE
Add capture duration to the UI and possible auto stop after duration.

### ISSUE THREAD

**Issue by IanSmallshire** [simoninns/DomesdayDuplicator#32]
Add user feedback for the amount of time elapsed on the current capture. 
Possible to set auto stop time as max length of discs is ~70 mins.

**Comment by wondras** [comment]
This would be highly useful in some situations. For example, on several occasions I have been on trips where I try to squeeze disc capture in around other activities. When capturing with VirtualDub, I can set a 30 minute limit, start capturing on a CAV disc, and return hours later to continue with the next one.
Of course, if the capture app can monitor frame # via a serial connection, this becomes less important.

**Comment by simoninns** [comment]
Fixed in latest merge
