### ISSUE TITLE
Support for Windows OS

### ISSUE THREAD

**Issue by simoninns** [simoninns/DomesdayDuplicator#37]
Currently the Duplicator application is only compatible with Ubuntu/Linux.  It should be possible (using QT) to make the capture application cross-platform.

**Comment by simoninns** [comment]
The new GUI rewrite goes a long way towards this due to the streamlined USB class implementation.  There is still the issue of libusb on windows not supporting hotplug.  Also there needs to be a way to install drivers on windows for libusb (I tried zdiag, but it seems to have a very bad affect on a number of library calls).

**Comment by simoninns** [comment]
After commit  af09b16 the application is reported to compile on Mac OS cleanly; however attempting to capture causes the same libUSB error found on Windows (with the exception that hotplug is supported on Mac OS).  The primary debug response is: UsbCapture::run(): Transfer launch 0 failed with error: LIBUSB_ERROR_NOT_FOUND

**Comment by wondras** [comment]
According to https://github.com/tessel/node-usb/issues/61 on macOS you have to 'claim' the interface before you can transfer data. The solution posted here involves using internal methods, but there is a proper libusb_claim_interface() method that accomplishes the same thing.

Adding this line just after the call to libusb_open() makes the data transfers function correctly:
`responseCode = libusb_claim_interface(usbDeviceHandle, 0);`

**Comment by simoninns** [comment]
Seems like the configuration mechanism isn't functioning under Windows either.

**Comment by simoninns** [comment]
All fixed apart from device detach detection - I'll open a new issue for that though to stop things from being confusing
