### ISSUE TITLE
Text clipping in UI

### ISSUE THREAD

**Issue by wondras** [simoninns/DomesdayDuplicator#43]
Some labels/captions in the UI are being clipped, with somewhat different cicrumstances in both Ubuntu and macOS.

I am not aware of any special display or scaling settings on my ubuntu setup, though it is running in a VM. The Mac is an early 2013 Retina MacBook Pro with "best for retina" scaling option.

<img width="317" alt="mac-remote" src="https://user-images.githubusercontent.com/8431402/45933637-e1261300-bf5e-11e8-928d-30a033af59a4.png">
<img width="318" alt="mac-autocapture" src="https://user-images.githubusercontent.com/8431402/45933638-e1261300-bf5e-11e8-94e0-1f9473912002.png">
<img width="380" alt="mac-prefs-capture" src="https://user-images.githubusercontent.com/8431402/45933639-e1261300-bf5e-11e8-8f8f-a5948b20e955.png">
<img width="377" alt="mac-prefs-usb" src="https://user-images.githubusercontent.com/8431402/45933640-e1261300-bf5e-11e8-8aec-c69d984f1c5d.png">

![ubuntu-remote](https://user-images.githubusercontent.com/8431402/45933641-e1261300-bf5e-11e8-9681-fadf613b7f12.png)

![ubuntu-autocapture](https://user-images.githubusercontent.com/8431402/45933642-e1261300-bf5e-11e8-9d61-b1e2ccf3725f.png)

![ubuntu-main](https://user-images.githubusercontent.com/8431402/45933643-e1bea980-bf5e-11e8-948d-2a6e49f8ec56.png)

![ubuntu-prefs-capture](https://user-images.githubusercontent.com/8431402/45933644-e1bea980-bf5e-11e8-906c-5c35376853c9.png)

![ubuntu-prefs-usb](https://user-images.githubusercontent.com/8431402/45933645-e1bea980-bf5e-11e8-9b10-34349983e0ca.png)

**Comment by wondras** [comment]
Also noted that the middle radio button in the auto-capture dialog has a large outline around it, who knows why...

**Comment by simoninns** [comment]
> Also noted that the middle radio button in the auto-capture dialog has a large outline around it, who knows why...

That's the highlight for keyboard control (part of the OS) - the field tab ordering is incorrect, which is why it highlights the middle radio button rather than the top as you'd expect.

**Comment by simoninns** [comment]
Should all be looking much better in commit  b77ca87 - Please take a look at the mac and ubuntu GUIs and let me know if there are still issues

**Comment by wondras** [comment]
Tests good on macOS and Ubuntu.  As a side benefit, the UI seems to have the right amount of "air" in it, so it doesn't feel cramped or enormous.
