### ISSUE TITLE
CAV whole disk capture could (optionally) use "FR0" instead of a spindown/spinup...

### ISSUE THREAD

**Issue by happycube** [simoninns/DomesdayDuplicator#51]
It'd be a bit quicker and easier on the player, but no biggie.  I can see why one would want to try to get the lead in though.

**Comment by happycube** [comment]
CLD-V2800 is set to auto repeat by default (integer 1 of register c)
http://manuals.lddb.com/LD_Players/Pioneer/CLD/CLD-V2800/Pioneer-CLD-V2800-EN_Programmer_Guide.pdf

(What'd I'd do myself is put in a frame check - record the highest observed frame # and if it's gone from a high number to < 1000, it's restarted and should stop.)

**Comment by simoninns** [comment]
I've added the suggested fix for this using a 'last seen address'.  The only possible impact I can think of, it it might get confused if a disc skips; but it will require more testing.  Fix is in commit 8a87aab
