### ISSUE TITLE
Advanged Capture Naming diaglog - needs more than 4 sides

### ISSUE THREAD

**Issue by IanSmallshire** [simoninns/DomesdayDuplicator#62]
Some CAV boxsets have more than 4 sides. 

I have seen 6 side boxset with extras but there may be one or more with 7+

With a serial connected player it should be possible to auto detect CAV/CLV PAL/NTSC and disc side A/B along with user code using Philips F-Codes (Unsure if available from Pioneer / Sony serial comms)

**Comment by simoninns** [comment]
Simple solution is to untick the sides and write it in the notes.  The notes are there as a free-text field when things don't fit.  Extending the GUI to suit every possible edge case would make it a mess :)
