### ISSUE TITLE
Test Data generated if application restarted and previous capture was test data.

### ISSUE THREAD

**Issue by IanSmallshire** [simoninns/DomesdayDuplicator#64]
To reproduce the issue.

Open the DomesdayDuplicator application
Turn  Edit > Test Mode to On.
Capture a few seconds (More than one)
Exit application
open application again (App defaults to test mode off but does not tell the FPGA its now off)
capture for a few seconds again.
close application

Open laserdisc analyser 
Test the first file generated (Expected test data) and verifies OK.
Test the second file generated (Expected real data) and verifies OK and should fail.

**Comment by simoninns** [comment]
Fixed in development branch - GUI now issues USB device configuration (vendor specific command) to set the test-mode off whenever the device is attached by the application (including on start-up).
