### ISSUE TITLE
Support for raw file output from HackTV and ignore functions of .json files

### ISSUE THREAD

**Issue by Zcooger** [simoninns/DomesdayDuplicator#78]
Hello, I have some raw composite video samples in PAL format that are using different precision. It will be useful to add support for these formats. They were generated by HackTV transmitter for HackRF:
https://github.com/fsphil/hacktv/blob/c4294769b2948825622be9b78a4d2c6b1bd61bb9/file.c
I provide them here as follows (change extension to raw):

    * UINT8: [uint8.raw.txt](https://github.com/Tee0125/yuvplayer/files/2829527/uint8.raw.txt)

    * INT8: [int8.raw.txt](https://github.com/Tee0125/yuvplayer/files/2829540/int8.raw.txt)

    * INT16: [int16.raw.txt](https://github.com/Tee0125/yuvplayer/files/2829544/int16.raw.txt)

    * INT32: [int32.raw.txt](https://github.com/Tee0125/yuvplayer/files/2829551/int32.raw.txt)

    * Float: [float.raw.txt](https://github.com/Tee0125/yuvplayer/files/2829563/float.raw.txt)
      The resolution is 896 x 625 so the resulting sample rate is 14MHz.

![cvbs](https://user-images.githubusercontent.com/42012614/52286588-c03be880-2968-11e9-9d52-60ef7835797b.png)

HackTV files are similar to baseband .tbc files generated from .lds capture. They similar but may use different precision/bit depth. As shown above HackTV produces split view of both fields at once.
If original .tbc file is replaced by .raw file from HackTV the result is:
![51240453_401655197259808_6469966518837837824_n](https://user-images.githubusercontent.com/42012614/52287128-de561880-2969-11e9-9756-0ffa2e06e494.png)
After adjusting output sample rate (17734472 Hz) based on .json file the result is:
![51255434_418773355529692_9168886700213010432_n](https://user-images.githubusercontent.com/42012614/52287153-f037bb80-2969-11e9-81c1-f76140f8dac6.png)

**Comment by simoninns** [comment]
This issue pertains to the ld-decode project (not the Domesday Duplicator - which is a hardware based LaserDisc capture device).  Please post it in the correct github :)
