### ISSUE TITLE
LaserDiscAnalyser should be renamed to avoid confusion

### ISSUE THREAD

**Issue by Gamnn** [simoninns/DomesdayDuplicator#80]
LaserDiscAnalyser is named too closely to ld-analyse, which can confuse people starting out.

Could it be renamed to LaserDiscVerifier or LaserDiscChecker perhaps? Including the option to export samples, ld-checkandsplit might work.

**Comment by simoninns** [comment]
Renamed to dddutil so it's in-line with dddconv and cannot be confused with the ld-decode tool-chain
