### ISSUE TITLE
Add mint mark field to advanced naming window

### ISSUE THREAD

**Issue by Gamnn** [simoninns/DomesdayDuplicator#93]
Turns out the specific master used to press the LD side can be important when it comes to ld-combine. It would be helpful if the DomesdayDuplicator app had a place to enter the side's mint marks to remind/encourage noting of them.

[Disc sides seem to have two mint marks](https://www.lddb.com/mint-o-matic.php)- the plastic batch number, and the video master reference. The latter is the important one here.
[This page shows examples](http://www.blamld.com/LaserDisc/Manufacturers.htm) from different manufacturers.

Note that because disc sides are pressed separately, then glued together to form a disc, two discs could could be identical on one side, but differ on the other.

**Comment by TokugawaHeavyIndustries** [comment]
This can be closed, #113
